FROM linuxcontainers/debian-slim
MAINTAINER Dave Billin <db77junk@gmail.com>

#####################
# DOCKER PARAMETERS:
# CTRUSER the name of a non-root user account to create in the container image
# CTRUID user ID in the host system given to the CTRUSER account in the container image
# CTRGID group ID in the host system given to the CTRUSER account in the container image

# Install common packages
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    apt-transport-https \
    apt-utils \
    bash-completion \
    ca-certificates \
    curl \
    gpgv \
    gnupg \
    openssh-client \
    software-properties-common \
    sudo \
    wget \
    xz-utils \
  && apt-get -y autoremove \
  && apt-get -y clean


# Install JUCE dependencies
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    libasound2-dev \
    libjack-jackd2-dev \
    ladspa-sdk \
    libcurl4-openssl-dev \
    libfreetype6-dev \
    libx11-dev \
    libxcomposite-dev \
    libxcursor-dev \
    libxext-dev \
    libxinerama-dev \
    libxrandr-dev \
    libxrender-dev \
    libwebkit2gtk-4.0-dev \
    libglu1-mesa-dev \
    mesa-common-dev \
 && apt-get -y autoremove \
 && apt-get -y clean

# Install additional development utilities
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    doxygen \
    git \
  && apt-get -y autoremove \
  && apt-get -y clean

# Install build tools
COPY ./llvm-15.list /etc/apt/sources.list.d/llvm-14.list
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - \
  && export DEBIAN_FRONTEND=noninteractive \
  && apt-get update \
  && apt-get install -y \
    cmake \
    clang-format \
    clang-tidy \
    clang-tools \
    clang clangd \
    libc++-dev \
    libc++1 \
    libc++abi-dev \
    libc++abi1 \
    libclang-dev \
    libclang1 \
    liblldb-dev \
    libllvm-ocaml-dev \
    libomp-dev \
    libomp5 \
    lld \
    lldb \
    llvm-dev \
    llvm-runtime \
    llvm \
    python3-clang \
  && apt-get -y autoremove \
  && apt-get -y clean

# Install PulseAudio packages and Carla VST host from KXStudio repositories
RUN wget https://launchpad.net/~kxstudio-debian/+archive/kxstudio/+files/kxstudio-repos_11.1.0_all.deb \
  && dpkg --install kxstudio-repos_11.1.0_all.deb \
  && rm kxstudio-repos_11.1.0_all.deb \
  && apt-get update \
  && apt-get install -y --no-install-recommends \
    carla \
    libpulse0 \
    libasound2 \
    libasound2-plugins \
  && apt-get -y autoremove \
  && apt-get -y clean

# Set up docker args for the container username
ARG CTRUSER
ARG CTRUID
ARG CTRGID

# Set up a vscode user that has the same user and group ID as the host environment user
RUN groupadd --gid $CTRGID $CTRUSER \
    && useradd -s /bin/bash --uid $CTRUID --gid $CTRGID -m $CTRUSER \
    && echo $CTRUSER ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$CTRUSER\
    && chmod +x /etc/sudoers.d/$CTRUSER

# Set up git prompt in the container's bash terminal
COPY git-prompt-bashrc-fragment /tmp/gitprompt
RUN mkdir -p /home/$CTRUSER/.bash-git \
    && for f in git-completion.bash git-prompt.sh; do \
       wget -q -O /home/$CTRUSER/.bash-git/${f} "https://raw.githubusercontent.com/git/git/master/contrib/completion/${f}"; \
       done \
    && cat /tmp/gitprompt >>/home/$CTRUSER/.bashrc

USER $CTRUSER

ENTRYPOINT [ "bash" ]
